rootProject.name = "inteli-framework"
include("scoreboard")
include("config")
include("commons")
include("hologram")
include("test-plugin")
include("adapters")
include("task")
include("item")
include("plugin")
include("command")
include("command-bukkit")
include("recipe")
include("packet-injector")
include("message")
include("menu")
