# Commands settings
global:
  # What should be the amount of commands to be split into paged?
  paged-commands-since: 10

  # Global variables that you can use with {variable}
  variables:
    main-color: "&a"
    secondary-color: "&b"
    markup-color: "&7"

  paged-message:
    # First line of the message
    1: "{main-color}&l---------[ {secondary-color}{command_label} {markup-color}Page {page}/{pages} {main-color}&l]---------"

    # Third line
    3: "{main-color}&l------------------"

    # Our commands template
    2:
      type: template
      content: "{command-usage}"

# Usages of commands
usages:
  "mines":
    message:
      - ""
      - "[sub elements]"

    # Sub command
    edit:
      message: "/mines <player> edit"

# All available commands on this registry
commands:
  # The name of command element defined in code
  mines:
    # If the command is enabled
    enabled: true

    # Custom name of command element
    name: "testCmd2"

    # The sub elements of this command
    mine:
      name: "mine"


