test-action-bar-message:
  type: action-bar
  text: "Hello!"

test-boss-bar-message:
  type: boss-bar
  text: "Hello!"
  props:
    color: blue
    percentage: 0.1
    stay: 20
    overlay: notched_20

test-title-message:
  type: title

  title: "Hello!"
  subtitle: "Hello2!"

  props:
    fade-in: 10
    fade-out: 200
    stay: 20


